<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <AssemblyName>STS2iOS</AssemblyName>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>..\..\lib\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GodotSharp">
      <HintPath>..\..\lib\GodotSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="sts2">
      <HintPath>..\..\lib\sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Steamworks.NET">
      <HintPath>..\..\lib\Steamworks.NET.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Sentry">
      <HintPath>..\..\lib\Sentry.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Steam\**" />
    <Compile Remove="Launcher\**" />
  </ItemGroup>
</Project>
